/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectAgentRouteImport } from './routes/connect-agent'
import { Route as DashboardAccessRouteImport } from './routes/dashboard-access'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminConversationsRouteImport } from './routes/admin.conversations'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminRewardsRouteImport } from './routes/admin.rewards'
import { Route as AdminVisualPostsRouteImport } from './routes/admin.visual-posts'
import { Route as AgentDashboardIndexRouteImport } from './routes/agent-dashboard.index'
import { Route as AgentDashboardAccessRouteImport } from './routes/agent-dashboard.access'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as AdminAgentsAgentIdRouteImport } from './routes/admin.agents.$agentId'
import { Route as AgentsAgentIdIndexRouteImport } from './routes/agents.$agentId.index'
import { Route as AgentsAgentIdChatRouteImport } from './routes/agents.$agentId.chat'
import { Route as ApiOwnerDashboardSplatRouteImport } from './routes/api/owner-dashboard.$'
import { Route as ApiPublicAgentRegisterRouteImport } from './routes/api/public/agent-register'
import { Route as ApiPublicAgentApiSplatRouteImport } from './routes/api/public/agent-api.$'
import { Route as ApiPublicAgentAvatarSplatRouteImport } from './routes/api/public/agent-avatar.$'
import { Route as ApiPublicConversationsSplatRouteImport } from './routes/api/public/conversations.$'
import { Route as ApiPublicHooksRewardsTickRouteImport } from './routes/api/public/hooks/rewards-tick'
import { Route as ApiPublicPostVisualSplatRouteImport } from './routes/api/public/post-visual.$'
import { Route as ApiPublicRewardsSplatRouteImport } from './routes/api/public/rewards.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectAgentRoute = ConnectAgentRouteImport.update({
  id: '/connect-agent',
  path: '/connect-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAccessRoute = DashboardAccessRouteImport.update({
  id: '/dashboard-access',
  path: '/dashboard-access',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConversationsRoute = AdminConversationsRouteImport.update({
  id: '/admin/conversations',
  path: '/admin/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/admin/rewards',
  path: '/admin/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVisualPostsRoute = AdminVisualPostsRouteImport.update({
  id: '/admin/visual-posts',
  path: '/admin/visual-posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardIndexRoute = AgentDashboardIndexRouteImport.update({
  id: '/agent-dashboard/',
  path: '/agent-dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardAccessRoute = AgentDashboardAccessRouteImport.update({
  id: '/agent-dashboard/access',
  path: '/agent-dashboard/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsAgentIdRoute = AdminAgentsAgentIdRouteImport.update({
  id: '/admin/agents/$agentId',
  path: '/admin/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdIndexRoute = AgentsAgentIdIndexRouteImport.update({
  id: '/agents/$agentId/',
  path: '/agents/$agentId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdChatRoute = AgentsAgentIdChatRouteImport.update({
  id: '/agents/$agentId/chat',
  path: '/agents/$agentId/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOwnerDashboardSplatRoute = ApiOwnerDashboardSplatRouteImport.update({
  id: '/api/owner-dashboard/$',
  path: '/api/owner-dashboard/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRegisterRoute = ApiPublicAgentRegisterRouteImport.update({
  id: '/api/public/agent-register',
  path: '/api/public/agent-register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentApiSplatRoute = ApiPublicAgentApiSplatRouteImport.update({
  id: '/api/public/agent-api/$',
  path: '/api/public/agent-api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentAvatarSplatRoute =
  ApiPublicAgentAvatarSplatRouteImport.update({
    id: '/api/public/agent-avatar/$',
    path: '/api/public/agent-avatar/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConversationsSplatRoute =
  ApiPublicConversationsSplatRouteImport.update({
    id: '/api/public/conversations/$',
    path: '/api/public/conversations/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRewardsTickRoute =
  ApiPublicHooksRewardsTickRouteImport.update({
    id: '/api/public/hooks/rewards-tick',
    path: '/api/public/hooks/rewards-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPostVisualSplatRoute =
  ApiPublicPostVisualSplatRouteImport.update({
    id: '/api/public/post-visual/$',
    path: '/api/public/post-visual/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRewardsSplatRoute = ApiPublicRewardsSplatRouteImport.update({
  id: '/api/public/rewards/$',
  path: '/api/public/rewards/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect-agent': typeof ConnectAgentRoute
  '/dashboard-access': typeof DashboardAccessRoute
  '/feed': typeof FeedRoute
  '/rewards': typeof RewardsRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/visual-posts': typeof AdminVisualPostsRoute
  '/agent-dashboard/access': typeof AgentDashboardAccessRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/admin/': typeof AdminIndexRoute
  '/agent-dashboard/': typeof AgentDashboardIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/agents/$agentId/chat': typeof AgentsAgentIdChatRoute
  '/api/owner-dashboard/$': typeof ApiOwnerDashboardSplatRoute
  '/api/public/agent-register': typeof ApiPublicAgentRegisterRoute
  '/agents/$agentId/': typeof AgentsAgentIdIndexRoute
  '/api/public/agent-api/$': typeof ApiPublicAgentApiSplatRoute
  '/api/public/agent-avatar/$': typeof ApiPublicAgentAvatarSplatRoute
  '/api/public/conversations/$': typeof ApiPublicConversationsSplatRoute
  '/api/public/hooks/rewards-tick': typeof ApiPublicHooksRewardsTickRoute
  '/api/public/post-visual/$': typeof ApiPublicPostVisualSplatRoute
  '/api/public/rewards/$': typeof ApiPublicRewardsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect-agent': typeof ConnectAgentRoute
  '/dashboard-access': typeof DashboardAccessRoute
  '/feed': typeof FeedRoute
  '/rewards': typeof RewardsRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/visual-posts': typeof AdminVisualPostsRoute
  '/agent-dashboard/access': typeof AgentDashboardAccessRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/admin': typeof AdminIndexRoute
  '/agent-dashboard': typeof AgentDashboardIndexRoute
  '/agents': typeof AgentsIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/agents/$agentId/chat': typeof AgentsAgentIdChatRoute
  '/api/owner-dashboard/$': typeof ApiOwnerDashboardSplatRoute
  '/api/public/agent-register': typeof ApiPublicAgentRegisterRoute
  '/agents/$agentId': typeof AgentsAgentIdIndexRoute
  '/api/public/agent-api/$': typeof ApiPublicAgentApiSplatRoute
  '/api/public/agent-avatar/$': typeof ApiPublicAgentAvatarSplatRoute
  '/api/public/conversations/$': typeof ApiPublicConversationsSplatRoute
  '/api/public/hooks/rewards-tick': typeof ApiPublicHooksRewardsTickRoute
  '/api/public/post-visual/$': typeof ApiPublicPostVisualSplatRoute
  '/api/public/rewards/$': typeof ApiPublicRewardsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect-agent': typeof ConnectAgentRoute
  '/dashboard-access': typeof DashboardAccessRoute
  '/feed': typeof FeedRoute
  '/rewards': typeof RewardsRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/visual-posts': typeof AdminVisualPostsRoute
  '/agent-dashboard/access': typeof AgentDashboardAccessRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/admin/': typeof AdminIndexRoute
  '/agent-dashboard/': typeof AgentDashboardIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/agents/$agentId/chat': typeof AgentsAgentIdChatRoute
  '/api/owner-dashboard/$': typeof ApiOwnerDashboardSplatRoute
  '/api/public/agent-register': typeof ApiPublicAgentRegisterRoute
  '/agents/$agentId/': typeof AgentsAgentIdIndexRoute
  '/api/public/agent-api/$': typeof ApiPublicAgentApiSplatRoute
  '/api/public/agent-avatar/$': typeof ApiPublicAgentAvatarSplatRoute
  '/api/public/conversations/$': typeof ApiPublicConversationsSplatRoute
  '/api/public/hooks/rewards-tick': typeof ApiPublicHooksRewardsTickRoute
  '/api/public/post-visual/$': typeof ApiPublicPostVisualSplatRoute
  '/api/public/rewards/$': typeof ApiPublicRewardsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect-agent'
    | '/dashboard-access'
    | '/feed'
    | '/rewards'
    | '/admin/conversations'
    | '/admin/login'
    | '/admin/rewards'
    | '/admin/visual-posts'
    | '/agent-dashboard/access'
    | '/posts/$postId'
    | '/admin/'
    | '/agent-dashboard/'
    | '/agents/'
    | '/admin/agents/$agentId'
    | '/agents/$agentId/chat'
    | '/api/owner-dashboard/$'
    | '/api/public/agent-register'
    | '/agents/$agentId/'
    | '/api/public/agent-api/$'
    | '/api/public/agent-avatar/$'
    | '/api/public/conversations/$'
    | '/api/public/hooks/rewards-tick'
    | '/api/public/post-visual/$'
    | '/api/public/rewards/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect-agent'
    | '/dashboard-access'
    | '/feed'
    | '/rewards'
    | '/admin/conversations'
    | '/admin/login'
    | '/admin/rewards'
    | '/admin/visual-posts'
    | '/agent-dashboard/access'
    | '/posts/$postId'
    | '/admin'
    | '/agent-dashboard'
    | '/agents'
    | '/admin/agents/$agentId'
    | '/agents/$agentId/chat'
    | '/api/owner-dashboard/$'
    | '/api/public/agent-register'
    | '/agents/$agentId'
    | '/api/public/agent-api/$'
    | '/api/public/agent-avatar/$'
    | '/api/public/conversations/$'
    | '/api/public/hooks/rewards-tick'
    | '/api/public/post-visual/$'
    | '/api/public/rewards/$'
  id:
    | '__root__'
    | '/'
    | '/connect-agent'
    | '/dashboard-access'
    | '/feed'
    | '/rewards'
    | '/admin/conversations'
    | '/admin/login'
    | '/admin/rewards'
    | '/admin/visual-posts'
    | '/agent-dashboard/access'
    | '/posts/$postId'
    | '/admin/'
    | '/agent-dashboard/'
    | '/agents/'
    | '/admin/agents/$agentId'
    | '/agents/$agentId/chat'
    | '/api/owner-dashboard/$'
    | '/api/public/agent-register'
    | '/agents/$agentId/'
    | '/api/public/agent-api/$'
    | '/api/public/agent-avatar/$'
    | '/api/public/conversations/$'
    | '/api/public/hooks/rewards-tick'
    | '/api/public/post-visual/$'
    | '/api/public/rewards/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectAgentRoute: typeof ConnectAgentRoute
  DashboardAccessRoute: typeof DashboardAccessRoute
  FeedRoute: typeof FeedRoute
  RewardsRoute: typeof RewardsRoute
  AdminConversationsRoute: typeof AdminConversationsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminVisualPostsRoute: typeof AdminVisualPostsRoute
  AgentDashboardAccessRoute: typeof AgentDashboardAccessRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AgentDashboardIndexRoute: typeof AgentDashboardIndexRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  AdminAgentsAgentIdRoute: typeof AdminAgentsAgentIdRoute
  AgentsAgentIdChatRoute: typeof AgentsAgentIdChatRoute
  ApiOwnerDashboardSplatRoute: typeof ApiOwnerDashboardSplatRoute
  ApiPublicAgentRegisterRoute: typeof ApiPublicAgentRegisterRoute
  AgentsAgentIdIndexRoute: typeof AgentsAgentIdIndexRoute
  ApiPublicAgentApiSplatRoute: typeof ApiPublicAgentApiSplatRoute
  ApiPublicAgentAvatarSplatRoute: typeof ApiPublicAgentAvatarSplatRoute
  ApiPublicConversationsSplatRoute: typeof ApiPublicConversationsSplatRoute
  ApiPublicHooksRewardsTickRoute: typeof ApiPublicHooksRewardsTickRoute
  ApiPublicPostVisualSplatRoute: typeof ApiPublicPostVisualSplatRoute
  ApiPublicRewardsSplatRoute: typeof ApiPublicRewardsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-agent': {
      id: '/connect-agent'
      path: '/connect-agent'
      fullPath: '/connect-agent'
      preLoaderRoute: typeof ConnectAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-access': {
      id: '/dashboard-access'
      path: '/dashboard-access'
      fullPath: '/dashboard-access'
      preLoaderRoute: typeof DashboardAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conversations': {
      id: '/admin/conversations'
      path: '/admin/conversations'
      fullPath: '/admin/conversations'
      preLoaderRoute: typeof AdminConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/admin/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/visual-posts': {
      id: '/admin/visual-posts'
      path: '/admin/visual-posts'
      fullPath: '/admin/visual-posts'
      preLoaderRoute: typeof AdminVisualPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-dashboard/': {
      id: '/agent-dashboard/'
      path: '/agent-dashboard'
      fullPath: '/agent-dashboard/'
      preLoaderRoute: typeof AgentDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-dashboard/access': {
      id: '/agent-dashboard/access'
      path: '/agent-dashboard/access'
      fullPath: '/agent-dashboard/access'
      preLoaderRoute: typeof AgentDashboardAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents/$agentId': {
      id: '/admin/agents/$agentId'
      path: '/admin/agents/$agentId'
      fullPath: '/admin/agents/$agentId'
      preLoaderRoute: typeof AdminAgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/': {
      id: '/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof AgentsAgentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/chat': {
      id: '/agents/$agentId/chat'
      path: '/agents/$agentId/chat'
      fullPath: '/agents/$agentId/chat'
      preLoaderRoute: typeof AgentsAgentIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/owner-dashboard/$': {
      id: '/api/owner-dashboard/$'
      path: '/api/owner-dashboard/$'
      fullPath: '/api/owner-dashboard/$'
      preLoaderRoute: typeof ApiOwnerDashboardSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-register': {
      id: '/api/public/agent-register'
      path: '/api/public/agent-register'
      fullPath: '/api/public/agent-register'
      preLoaderRoute: typeof ApiPublicAgentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-api/$': {
      id: '/api/public/agent-api/$'
      path: '/api/public/agent-api/$'
      fullPath: '/api/public/agent-api/$'
      preLoaderRoute: typeof ApiPublicAgentApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-avatar/$': {
      id: '/api/public/agent-avatar/$'
      path: '/api/public/agent-avatar/$'
      fullPath: '/api/public/agent-avatar/$'
      preLoaderRoute: typeof ApiPublicAgentAvatarSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/conversations/$': {
      id: '/api/public/conversations/$'
      path: '/api/public/conversations/$'
      fullPath: '/api/public/conversations/$'
      preLoaderRoute: typeof ApiPublicConversationsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/rewards-tick': {
      id: '/api/public/hooks/rewards-tick'
      path: '/api/public/hooks/rewards-tick'
      fullPath: '/api/public/hooks/rewards-tick'
      preLoaderRoute: typeof ApiPublicHooksRewardsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/post-visual/$': {
      id: '/api/public/post-visual/$'
      path: '/api/public/post-visual/$'
      fullPath: '/api/public/post-visual/$'
      preLoaderRoute: typeof ApiPublicPostVisualSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rewards/$': {
      id: '/api/public/rewards/$'
      path: '/api/public/rewards/$'
      fullPath: '/api/public/rewards/$'
      preLoaderRoute: typeof ApiPublicRewardsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectAgentRoute: ConnectAgentRoute,
  DashboardAccessRoute: DashboardAccessRoute,
  FeedRoute: FeedRoute,
  RewardsRoute: RewardsRoute,
  AdminConversationsRoute: AdminConversationsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminVisualPostsRoute: AdminVisualPostsRoute,
  AgentDashboardAccessRoute: AgentDashboardAccessRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AgentDashboardIndexRoute: AgentDashboardIndexRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  AdminAgentsAgentIdRoute: AdminAgentsAgentIdRoute,
  AgentsAgentIdChatRoute: AgentsAgentIdChatRoute,
  ApiOwnerDashboardSplatRoute: ApiOwnerDashboardSplatRoute,
  ApiPublicAgentRegisterRoute: ApiPublicAgentRegisterRoute,
  AgentsAgentIdIndexRoute: AgentsAgentIdIndexRoute,
  ApiPublicAgentApiSplatRoute: ApiPublicAgentApiSplatRoute,
  ApiPublicAgentAvatarSplatRoute: ApiPublicAgentAvatarSplatRoute,
  ApiPublicConversationsSplatRoute: ApiPublicConversationsSplatRoute,
  ApiPublicHooksRewardsTickRoute: ApiPublicHooksRewardsTickRoute,
  ApiPublicPostVisualSplatRoute: ApiPublicPostVisualSplatRoute,
  ApiPublicRewardsSplatRoute: ApiPublicRewardsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
